trigger: none

pool: may-pool

# For Linting

stages:
  - stage: Lint
    displayName: Lint process
    jobs:
      - job: terraformlint
        steps:
          - task: PowerShell@2
            displayName: Install TFLint
            inputs:
             targetType: 'inline'
             script: |
              Invoke-WebRequest -Uri "https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip" -OutFile "tflint.zip"
              Expand-Archive -Path "tflint.zip" -DestinationPath ".\tflint"
              $env:PATH += ";$(System.DefaultWorkingDirectory)\tflint"
              .\tflint\tflint.exe --version

  # For Terraform Init

  - stage: Init
    displayName: Terraform Init
    dependsOn: Lint
    jobs:
      - job: terraforminit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'may.tfstate'

  # For Terraform Validate

  - stage: Validate
    displayName: Terraform Validate
    dependsOn: Init
    jobs:
      - job: terraformvalidate
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'may.tfstate'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'

 # For securityScan

  - stage: SecurityScan
    displayName: Checkov Security Scan
    dependsOn: Validate
    jobs:
      - job: checkovjob
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'may.tfstate'

          - task: PowerShell@2
            displayName: Security Scan - Checkov
            inputs:
              targetType: 'inline'
              script: |
               python -m pip install --upgrade pip
               python -m pip install checkov
               python -m checkov -d "$(System.DefaultWorkingDirectory)"

  # For Terraform Plan
  - stage: TerraformPlan
    displayName: Plan
    dependsOn: SecurityScan
    jobs:
      - job: terraformplan
        steps:
           - task: TerraformTask@5
             inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'may.tfstate'

           - task: TerraformTask@5
             inputs:
               provider: 'azurerm'
               command: 'plan'
               environmentServiceNameAzureRM: 'may-sc'

  # For Terraform apply
  - stage: TerraformApply
    displayName: Apply
    dependsOn: TerraformPlan
    jobs:
      - job: terraformapply
        steps:
           - task: TerraformTask@5
             inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'may-sc'
              backendAzureRmStorageAccountName: 'maystg12'
              backendAzureRmContainerName: 'maycnt12'
              backendAzureRmKey: 'may.tfstate'

           - task: TerraformTask@5
             inputs:
               provider: 'azurerm'
               command: 'apply'
               environmentServiceNameAzureRM: 'may-sc'
